- web:
    SHORTTITLE: Tyler Chang MCS@ANL
    BGIMAGE: img/delvor.png
    BGCOLOR: rgba(250, 250, 255, 0.9)
    FGCOLOR: rgba(255, 255, 255, 1.0)

- me:
    name: Tyler H. Chang
    alias:
        - T. H. Chang
    institution: Argonne National Laboratory
    department: Mathematics & Computer Science (MCS) Division
    address: 9700 S. Cass Ave, Bldg. 240, Lemont, IL 60439
    image: img/profile_2022_web.jpg
    email: tchang@anl.gov
    website: https://thchang.github.io
    links:
        github: https://github.com/thchang
        scholar: https://scholar.google.com/citations?user=XvFLOWsAAAAJ&hl=en
        linkedin: https://www.linkedin.com/in/tyler-chang-2524b9182
        orcid: https://orcid.org/0000-0001-9541-7041
        twitter: https://twitter.com/thchang94
        My CV: ./cv.pdf
    images:
        email: img/email-icon.png
        github: img/github-icon.png
        scholar: img/scholar-icon.png
        linkedin: img/linkedin-icon.png
        orcid: img/orcid-icon.png
        twitter: img/twitter-icon.png

- advisor:
    name: Layne T. Watson
    type: phd
    institution: Virginia Tech
    website: https://people.cs.vt.edu/~ltw/shortvita.html

- advisor:
    name: Stefan M. Wild
    type: postdoc
    institution: Lawrence Berkley National Laboratory
    website: https://wildsm.github.io

- advisee:
    name: Student Name2
    type: summer student via Other DOE Internship program
    institution: Some University2
    wesbite: https://www.youtube.com
    year: Jun 2021 - Aug 2021
    description:
        - "Project: YouTubing stuff"

- advisee:
    name: Student Name1
    type: summer student via Argonne Internship program
    institution: Some University1
    wesbite: https://www.google.com
    year: Jun 2020 - Aug 2020
    description:
        - "Project: googling stuff"

- mentee:
    name: Mentee Name
    type: friend via Argonne friendship program
    institution: Some University
    wesbite: https://www.facebook.com
    year: Jun 2020
    description:
        - "Friendship level: OK"

- collaborator:
    name: Thomas C. H. Lux
    institution: Meta Research
    website: https://tchlux.github.io
