- web:
    SHORTTITLE: Tyler Chang - Argonne National Laboratory
    BGIMAGE: img/delvor.png
    BGCOLOR: rgba(250, 250, 255, 0.9)
    FGCOLOR: rgba(255, 255, 255, 1.0)

- me:
    name: Tyler H. Chang
    alias:
        - T. H. Chang
    institution: Argonne National Laboratory
    department: Mathematics & Computer Science (MCS) Division
    address: 9700 S. Cass Ave, Bldg. 240, Lemont, IL 60439
    image: img/profile_2022_web.jpg
    email: tchang@anl.gov
    website: https://thchang.github.io
    links:
        GitHub: https://github.com/thchang
        Scholar: https://scholar.google.com/citations?user=XvFLOWsAAAAJ&hl=en
        LinkedIn: https://www.linkedin.com/in/tyler-chang-2524b9182
        Orcid: https://orcid.org/0000-0001-9541-7041
        Twitter: https://twitter.com/thchang94
    images:
        email: img/email-icon.png
        GitHub: img/github-icon.png
        Scholar: img/scholar-icon.png
        LinkedIn: img/linkedin-icon.png
        Orcid: img/orcid-icon.png
        Twitter: img/twitter-icon.png
    tabs:
        CV: ./cv.pdf

- advisor:
    name: Jeffrey Larson
    start: Dec 2022
    type: Postdoctoral advisor
    institution: Argonne
    website: https://jmlarson1.github.io/
    description:
        - Current postdoctoral advisor and 2019 DOE SCGSR advisor
        - 'Ongoing collaborations in applications of multiobjective optimization and usage of <a href="https://libensemble.readthedocs.io/en/latest">libEnsemble</a> in multiobjective solvers'

- advisor:
    name: Stefan Wild
    start: Jun 2020
    end: Dec 2022
    type: Postdoctoral advisor
    institution: Lawrence Berkeley National Lab
    website: https://wildsm.github.io
    description:
        - Advised 2.5 years of postdoc at Argonne
        - 'Ongoing collaborations in design and applications of <a href="https://parmoo.readthedocs.io/en/latest">ParMOO software</a>'

- advisor:
    name: Layne Watson
    start: Aug 2016
    end: May 2020
    type: PhD advisor
    institution: Virginia Tech
    website: https://people.cs.vt.edu/~ltw/shortvita.html
    description:
        - 'Advised dissertation: <a href="https://vtechworks.lib.vt.edu/handle/10919/98915">Mathematical Software for Multiobjective Optimization Problems</a>'
        - Ongoing collaborations in numerical software, blackbox optimization, and approximation theory

- collaborator:
    name: Andrew Gillette
    institution: Lawrence Livermore National Lab
    type: collaborator
    website: https://akgillette.github.io/
    description:
        - 'Early user of the <a href="https://vtopt.github.io/DelaunaySparse">DelaunaySparse</a> software and coinvestigator into its applications in data science'
        - Ongoing collaborations in geometric and topologic methods for machine learning and data science

- collaborator:
    name: Thomas Lux
    institution: Meta Research
    type: academic brother, collaborator, friend
    website: https://tchlux.github.io
    description:
        - 'Math & algorithms teammate on the <a href="https://varsys.cs.vt.edu/">VarSys project at VT</a> and test-user of <a href="https://vtopt.github.io/DelaunaySparse">DelaunaySparse</a> software'
        - Ongoing collaborations in software maintenance, performance optimization, and co-oping all Halo campaigns on legendary difficulty

- advisee:
    name: Hyrum Dickinson
    type: DOE SULI at Argonne
    website: https://www.linkedin.com/in/hyrum-dickinson-6b28301b7/
    institution: Urbana-Champaign
    start: Jun 2022
    end: Aug 2022
    description:
        - "Project: Visualization tools for the ParMOO library"
    alias:
        - "H. Dickinson"

- advisee:
    name: Manisha Garg
    type: NSF MSGI at Argonne
    institution: Urbana-Champaign
    start: Jun 2022
    end: Aug 2022
    description:
        - "Project: Model agnostic sampling techniques for generating design-of-experiments"
    alias:
        - "M. Garg"

- mentee:
    name: Srinivas Eswar
    type: via Argonne Navigator Program
    institution: postdoc at Argonne
    year: Aug 2022

- mentee:
    name: Bosco Ndemeye
    type: via SIAM CSE Mentoring Program
    institution: PhD student at Univ. of Oregon
    year: Mar 2021

