- web:
    SHORTTITLE: Tyler Chang - Argonne National Laboratory
    BGIMAGE: img/delvor.png
    BGCOLOR: rgba(250, 250, 255, 0.9)
    FGCOLOR: rgba(255, 255, 255, 1.0)

- cv:
    COLOR: blue

- me:
    name: Tyler H. Chang
    alias:
        - T. H. Chang
    institution: Argonne National Laboratory
    department: Mathematics and Computer Science Division
    address: 9700 S. Cass Ave, Bldg. 240, Lemont, IL 60439
    image: img/profile_2022_web.jpg
    email: tchang@anl.gov
    website: https://thchang.github.io
    links:
        GitHub: https://github.com/thchang
        Scholar: https://scholar.google.com/citations?user=XvFLOWsAAAAJ&hl=en
        LinkedIn: https://www.linkedin.com/in/tyler-chang-2524b9182
        Orcid: https://orcid.org/0000-0001-9541-7041
        Twitter: https://twitter.com/thchang94
    images:
        email: img/email-icon.png
        GitHub: img/github-icon.png
        Scholar: img/scholar-icon.png
        LinkedIn: img/linkedin-icon.png
        Orcid: img/orcid-icon.png
        Twitter: img/twitter-icon.png
    tabs:
        CV: ./cv.pdf

- advisor:
    name: Stefan Wild
    institution: Director of Applied Mathematics and Computing, Lawrence Berkeley National Lab
    ttype: Postdoctoral supervisor
    website: https://wildsm.github.io
    description:
        - "Postdoctoral supervisor"
        - "Email: wild@lbl.gov"

- advisor:
    name: Layne Watson
    ttype: Ph.D. advisor
    institution: Professor of Mathematics, Computer Science, and Aerospace Engineering, Virginia Tech
    website: https://people.cs.vt.edu/~ltw/shortvita.html
    description:
        - "Ph.D. advisor"
        - "Email: ltw@cs.vt.edu"

- reference1:
    name: Jeffrey Larson
    institution: Senior Computational Mathematician, Argonne National Lab
    ttype: Current supervisor and internal collaborator
    website: https://jmlarson1.github.io/
    description:
        - "Supervisor and internal collaborator"
        - "Email: jmlarson@anl.gov"

- reference:
    name: Andrew Gillette
    institution: Computational Scientist, Lawrence Livermore National Lab
    ttype: External collaborator
    website: https://akgillette.github.io/
    description:
        - "External collaborator"
        - "Email: gillette7@llnl.gov"

- reference:
    name: Santanu Chaudhuri
    institution: Professor of Civil, Material, and Environmental Engineering, University of Illinois Chicago
    ttype: External collaborator
    website: https://m3l.uic.edu
    description:
        - "External collaborator"
        - "Email: santc@uic.edu"

- reference2:
    name: Kirk Cameron
    institution: Professor of Computer Science, Virginia Tech
    ttype: Former project PI
    website: https://wordpress.cs.vt.edu/cameron
    description:
        - "Former project PI. Email: cameron@cs.vt.edu"

- collaborator:
    name: Thomas Lux
    institution: Meta Research
    type: academic brother, collaborator, friend
    website: https://tchlux.github.io
    description:
        - 'Math & algorithms teammate on the <a href="https://varsys.cs.vt.edu/">VarSys project at VT</a> and test-user of <a href="https://vtopt.github.io/DelaunaySparse">DelaunaySparse</a> software'
        - Ongoing collaborations in software maintenance, performance optimization, and co-oping all Halo campaigns on legendary difficulty

- advisee:
    name: Manisha Garg
    type: NSF MSGI (PhD student intern) at Argonne
    institution: UIUC
    start: Jun 2022
    end: Aug 2022
    description:
        - "Project: Model agnostic sampling techniques for generating design-of-experiments"
    alias:
        - "M. Garg"

- advisee:
    name: Hyrum Dickinson
    type: DOE SULI (undergraduate intern) at Argonne
    website: https://www.linkedin.com/in/hyrum-dickinson-6b28301b7/
    institution: UIUC
    start: Jun 2022
    end: Aug 2022
    description:
        - "Project: Visualization tools for the ParMOO library"
    alias:
        - "H. Dickinson"

- mentee:
    name: Srinivas Eswar
    type: via Argonne Navigator Program
    institution: postdoc at Argonne
    year: Aug 2022

- mentee:
    name: Bosco Ndemeye
    type: via SIAM CSE Mentoring Program
    institution: PhD student at Univ. of Oregon
    year: Mar 2021

