- journalref:
    title: Optimization Methods and Software
    years: 2025--Present
    revs: 1 paper

- journalref:
    title: Journal of Supercomputing
    year: 2024--Present
    revs: 1 paper

- journalref:
    title: INFORMS Journal on Computing
    year: 2023--Present
    revs: 1 paper + 1 rev

- journalref:
    title: ACM Transactions on Mathematical Software
    year: 2021--Present
    revs: 1 paper + 1 rev

- journalref:
    title: Quantum Information Processing
    year: 2021--Present
    revs: 1 paper

- journalref:
    title: The Visual Computer Journal
    year: 2021
    revs: 1 paper

- journalref:
    title: 'MDPI: Mathematical and Computer Applications'
    year: 2021
    revs: 1 paper + 1 rev

- journalref:
    title: Journal of Machine Learning Research
    year: 2019
    revs: 1 paper

- confref:
    title: ICIAM
    year: 2023
    revs: 1 abstract

- confref:
    title: Supercomputing
    year: 2021
    revs: 3 papers

- confref:
    title: IEEE SoutheastCon
    year: 2018--2020
    revs: 12 papers

- minisymporg:
    title: Multiobjective Optimization Software track in SIAM Conference on Optimization
    year: 2021

- minisymporg:
    title: Geometric Methods for Machine Learning track in SIAM Conference on Computational Science and Engineering
    year: 2021

- member:
    title: ACM
    year: 2015--Present

- member:
    title: SIAM
    year: 2016--Present

- cod:
    start: Jan 2024
    title: Member of Computer and Information Science Advisory Board
    description:
        - Providing insight for planning course offerins in CIS

- cod:
    start: Aug 2023
    end: Sep 2023
    title: Faculty contact for Argonne visit
    description:
        - Organized for 20 students from College of DuPage to visit Argonne

- argonne:
    start: Nov 2022
    title: Organizing Committee
    institution: FASTMath Institute Seminar Series
    description:
        - Providing input on topics and recruiting seminar speakers

- argonne:
    start: Dec 2022
    end: Jan 2023
    title: Hiring Committee
    institution: MCS Division
    description:
        - Interviewing potential candidates for postdoctoral openings

- argonne:
    start: Oct 2022
    end: Dec 2022
    title: Technical Reviewer
    institution: Sustainable Research Pathways
    description:
        - Providing technical reviews of faculty and student submissions to SRP program

- argonne:
    start: Mar 2022
    end: Apr 2022
    title: Red Team Reviewer
    institution: ASCR Pre-proposals
    description:
        - Providing red team reviews of staff pre-proposals, for internal downselection for DOE ASCR FOAs

- virginiatech:
    start: Aug 2017
    end: May 2020
    title: Founding Member
    institution: Computer Science Graduate Counsel
    description:
        - Organized professional and social events for graduate students and communicated student concerns to faculty

- virginiatech:
    start: Dec 2018
    end: Mar 2019
    title: Lead Student Organizer
    institution: Computer Science Graduate Preview Weekend
    description:
        - Organized recruitment events for prospective graduate students and coordinated meetings with faculty
